/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ComparateurRouteImport } from './routes/comparateur'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparateurRoute = ComparateurRouteImport.update({
  id: '/comparateur',
  path: '/comparateur',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comparateur': typeof ComparateurRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comparateur': typeof ComparateurRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comparateur': typeof ComparateurRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/profil': typeof ProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/comment-ca-marche'
    | '/comparateur'
    | '/mentions-legales'
    | '/partenaires'
    | '/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/comment-ca-marche'
    | '/comparateur'
    | '/mentions-legales'
    | '/partenaires'
    | '/profil'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/comment-ca-marche'
    | '/comparateur'
    | '/mentions-legales'
    | '/partenaires'
    | '/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ComparateurRoute: typeof ComparateurRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PartenairesRoute: typeof PartenairesRoute
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparateur': {
      id: '/comparateur'
      path: '/comparateur'
      fullPath: '/comparateur'
      preLoaderRoute: typeof ComparateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ComparateurRoute: ComparateurRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PartenairesRoute: PartenairesRoute,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
